/**
 * All page initialization scripts collected here to avoid circular deps.
 * Page renderers import allPageScripts() to pass to renderShell().
 * Script functions return JS source strings that run inside the SPA shell.
 */

export function allPageScripts(): Record<string, string> {
  return {
    dashboard: dashboardScript(),
    conversations: conversationsScript(),
    context: contextScript(),
    ipc: ipcScript(),
  };
}

function dashboardScript(): string {
  return [
    'var tasksTable=document.getElementById("tasks-tbody");',
    'if(!tasksTable)return;',
    'tasksTable.addEventListener("click",function(e){',
    '  var btn=e.target.closest("button[data-action]");if(!btn)return;',
    '  var row=btn.closest("tr");var taskId=row.getAttribute("data-task-id");',
    '  var action=btn.getAttribute("data-action");',
    '  if(action==="toggle"){',
    '    var ns=btn.getAttribute("data-status");btn.disabled=true;',
    '    fetch("/api/tasks/"+encodeURIComponent(taskId),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:ns})})',
    '    .then(function(r){if(!r.ok)return r.json().then(function(d){throw new Error(d.error);});return r.json();})',
    '    .then(function(){window.__toast("Task "+(ns==="paused"?"paused":"resumed"));})',
    '    .catch(function(err){window.__toast(err.message||"Failed","error");btn.disabled=false;});',
    '  }',
    '  if(action==="delete"){',
    '    btn.disabled=true;',
    '    fetch("/api/tasks/"+encodeURIComponent(taskId),{method:"DELETE"})',
    '    .then(function(r){if(!r.ok)return r.json().then(function(d){throw new Error(d.error);});return r.json();})',
    '    .then(function(){window.__toast("Task deleted");row.remove();})',
    '    .catch(function(err){window.__toast(err.message||"Failed","error");btn.disabled=false;});',
    '  }',
    '});',
    '',
    'var modal=document.getElementById("create-task-modal");',
    'var form=document.getElementById("create-task-form");',
    'var errorEl=document.getElementById("ct-error");',
    'if(modal&&form){',
    '  document.getElementById("btn-create-task").addEventListener("click",function(){modal.classList.add("open");errorEl.textContent="";});',
    '  document.getElementById("ct-cancel").addEventListener("click",function(){modal.classList.remove("open");});',
    '  modal.addEventListener("click",function(e){if(e.target===modal)modal.classList.remove("open");});',
    '  form.addEventListener("submit",function(e){',
    '    e.preventDefault();errorEl.textContent="";',
    '    var sb=document.getElementById("ct-submit");sb.disabled=true;',
    '    var av=document.getElementById("ct-agent").value;',
    '    if(!av){errorEl.textContent="Select an agent";sb.disabled=false;return;}',
    '    var parts=av.split("|");',
    '    var payload={group_folder:parts[0],chat_jid:parts[1],prompt:document.getElementById("ct-prompt").value,',
    '      schedule_type:document.getElementById("ct-schedule-type").value,',
    '      schedule_value:document.getElementById("ct-schedule-value").value,',
    '      context_mode:document.getElementById("ct-context-mode").value};',
    '    fetch("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)})',
    '    .then(function(r){if(!r.ok)return r.json().then(function(d){throw new Error(d.error);});return r.json();})',
    '    .then(function(t){window.__toast("Task created: "+t.id.slice(0,12));modal.classList.remove("open");form.reset();})',
    '    .catch(function(err){errorEl.textContent=err.message||"Failed";sb.disabled=false;});',
    '  });',
    '}',
  ].join('\n');
}

function conversationsScript(): string {
  return [
    'var chatList=document.getElementById("chat-list");',
    'var convContent=document.getElementById("conv-content");',
    'var searchInput=document.getElementById("chat-search");',
    'var chatCountEl=document.getElementById("chat-count");',
    'if(!chatList)return;',
    'var currentJid=null;var messageCache={};var PAGE_SIZE=100;',
    '',
    'var params=new URLSearchParams(location.search);',
    'var initChat=params.get("chat");',
    'if(initChat){var ii=chatList.querySelector("[data-jid=\\""+CSS.escape(initChat)+"\\"]");',
    '  if(ii)setTimeout(function(){selectChat(initChat);},0);}',
    '',
    'searchInput.addEventListener("input",function(){',
    '  var q=this.value.toLowerCase();var items=chatList.querySelectorAll(".chat-item");var vis=0;',
    '  items.forEach(function(item){',
    '    var name=item.querySelector(".chat-name").textContent.toLowerCase();',
    '    var jid=item.getAttribute("data-jid").toLowerCase();',
    '    var show=name.indexOf(q)!==-1||jid.indexOf(q)!==-1;',
    '    item.style.display=show?"":"none";if(show)vis++;',
    '  });',
    '  chatCountEl.textContent=vis+" chat"+(vis!==1?"s":"");',
    '});',
    '',
    'chatList.addEventListener("click",function(e){',
    '  var item=e.target.closest(".chat-item");if(!item)return;selectChat(item.getAttribute("data-jid"));',
    '});',
    'chatList.addEventListener("keydown",function(e){',
    '  if(e.key==="Enter"){var item=e.target.closest(".chat-item");if(item)selectChat(item.getAttribute("data-jid"));}',
    '});',
    '',
    'function selectChat(jid){',
    '  if(jid===currentJid)return;currentJid=jid;',
    '  history.replaceState(null,"","/conversations?chat="+encodeURIComponent(jid));',
    '  chatList.querySelectorAll(".chat-item").forEach(function(el){',
    '    el.classList.toggle("selected",el.getAttribute("data-jid")===jid);',
    '  });',
    '  convContent.innerHTML=\'<div class="loading">Loading\\u2026</div>\';',
    '  loadMessages(jid);',
    '}',
    '',
    'function loadMessages(jid){',
    '  fetch("/api/messages/"+encodeURIComponent(jid)+"?limit="+PAGE_SIZE)',
    '  .then(function(r){if(!r.ok)throw new Error("Failed");return r.json();})',
    '  .then(function(msgs){',
    '    if(!Array.isArray(msgs))throw new Error("bad");',
    '    if(currentJid!==jid)return;messageCache[jid]=msgs;renderMessages(jid,msgs);',
    '  }).catch(function(){if(currentJid!==jid)return;convContent.innerHTML=\'<div class="loading">Failed to load</div>\';});',
    '}',
    '',
    'function renderMessages(jid,messages){',
    '  var ci=chatList.querySelector("[data-jid=\\""+CSS.escape(jid)+"\\"]");',
    '  var cn=ci?ci.querySelector(".chat-name").textContent:jid;',
    '  var h=\'<div class="message-header"><h2>\'+window.__esc(cn)+\'</h2>\'',
    '    +\'<span class="jid-label">\'+window.__esc(jid)+\'</span>\'',
    '    +\'<span class="msg-count">\'+messages.length+\' msg\'+(messages.length!==1?"s":"")+\'</span></div>\';',
    '  var lm=messages.length>=PAGE_SIZE?\'<div class="load-more-bar"><button class="btn btn-sm" id="btn-load-more">Load older</button></div>\':"";',
    '  var m=\'<div class="messages" id="messages-container">\';',
    '  if(messages.length===0)m+=\'<div class="loading">No messages</div>\';',
    '  else for(var i=0;i<messages.length;i++){',
    '    var msg=messages[i];var isMe=msg.sender==="me"||msg.sender==="bot"||msg.is_from_me;',
    '    var rc="msg-row"+(isMe?" from-me":"");',
    '    var time=new Date(msg.timestamp).toLocaleString();',
    '    var sn=msg.sender_name||msg.sender||"Unknown";',
    '    var text=msg.content||"";var dt=text.length>2000?text.slice(0,2000)+"\\u2026 [truncated]":text;',
    '    m+=\'<div class="\'+rc+\'"><div class="msg-bubble">\'',
    '      +\'<div class="msg-sender">\'+window.__esc(sn)+\'</div>\'',
    '      +\'<div class="msg-text">\'+window.__esc(dt)+\'</div>\'',
    '      +\'<div class="msg-time">\'+window.__esc(time)+\'</div>\'',
    '      +\'</div></div>\';',
    '  }',
    '  m+="</div>";',
    '  convContent.innerHTML=h+lm+m;',
    '  var container=document.getElementById("messages-container");',
    '  if(container)container.scrollTop=container.scrollHeight;',
    '  var lb=document.getElementById("btn-load-more");',
    '  if(lb)lb.addEventListener("click",function(){',
    '    lb.disabled=true;lb.textContent="Loading\\u2026";',
    '    fetch("/api/messages/"+encodeURIComponent(jid)+"?limit=500")',
    '    .then(function(r){if(!r.ok)throw new Error("fail");return r.json();})',
    '    .then(function(all){if(!Array.isArray(all))throw new Error("bad");if(currentJid!==jid)return;messageCache[jid]=all;renderMessages(jid,all);})',
    '    .catch(function(){lb.disabled=false;lb.textContent="Load older";});',
    '  });',
    '}',
  ].join('\n');
}

function contextScript(): string {
  return [
    'var currentLayer="channel",currentView="split",layerData={},editor=null,originalContent="",dirty=false,monacoReady=false;',
    'var ctxSidebar=document.querySelector(".ctx-sidebar");',
    'if(!ctxSidebar)return;',
    '',
    'function loadScript(src){return new Promise(function(ok,fail){',
    '  if(document.querySelector("script[src=\\""+src+"\\"]"))return ok();',
    '  var s=document.createElement("script");s.src=src;s.onload=ok;s.onerror=fail;document.head.appendChild(s);',
    '});}',
    '',
    'Promise.all([',
    '  loadScript("https://cdn.jsdelivr.net/npm/marked@15.0.7/marked.min.js"),',
    '  loadScript("https://cdn.jsdelivr.net/npm/monaco-editor@0.52.2/min/vs/loader.min.js")',
    ']).then(function(){',
    '  if(typeof require==="undefined"||!require.config)return;',
    '  require.config({paths:{vs:"https://cdn.jsdelivr.net/npm/monaco-editor@0.52.2/min/vs"}});',
    '  require(["vs/editor/editor.main"],function(){',
    '    monaco.editor.defineTheme("omniclaw",{base:"vs-dark",inherit:true,rules:[],colors:{',
    '      "editor.background":"#141821","editor.foreground":"#cdd2dc",',
    '      "editorLineNumber.foreground":"#3a3f52","editorLineNumber.activeForeground":"#636a7e",',
    '      "editor.lineHighlightBackground":"#1c2030","editor.selectionBackground":"#2e3450",',
    '      "editorCursor.foreground":"#818cf8"',
    '    }});',
    '    var container=document.getElementById("editor-container");',
    '    if(!container)return;',
    '    editor=monaco.editor.create(container,{',
    '      value:"",language:"markdown",theme:"omniclaw",minimap:{enabled:false},',
    '      fontSize:13,lineHeight:22,wordWrap:"on",scrollBeyondLastLine:false,',
    '      renderWhitespace:"selection",padding:{top:12},automaticLayout:true,tabSize:2',
    '    });',
    '    editor.onDidChangeModelContent(function(){',
    '      if(!monacoReady)return;var val=editor.getValue();dirty=val!==originalContent;',
    '      updateSaveBar();updatePreview(val);',
    '    });',
    '    editor.addCommand(monaco.KeyMod.CtrlCmd|monaco.KeyCode.KeyS,function(){if(dirty)saveChanges();});',
    '    monacoReady=true;',
    '  });',
    '}).catch(function(e){console.error("Failed to load editor:",e);});',
    '',
    'function updateUrl(agent,channel){',
    '  var p=new URLSearchParams(location.search);',
    '  if(agent!==undefined)p.set("agent",agent);',
    '  if(channel!==undefined)p.set("channel",channel);',
    '  if(currentLayer&&currentLayer!=="channel")p.set("layer",currentLayer);else p.delete("layer");',
    '  if(currentView&&currentView!=="split")p.set("view",currentView);else p.delete("view");',
    '  history.replaceState(null,"","/context?"+p.toString());',
    '}',
    '',
    'ctxSidebar.addEventListener("click",function(e){',
    '  var hdr=e.target.closest("[data-toggle-agent]");',
    '  if(hdr){hdr.querySelector(".chevron").classList.toggle("open");hdr.nextElementSibling.classList.toggle("open");return;}',
    '  var ch=e.target.closest("[data-select-channel]");',
    '  if(ch)selectChannel(ch);',
    '});',
    '',
    'function selectChannel(el){',
    '  document.querySelectorAll(".channel-item").forEach(function(c){c.classList.remove("active");});',
    '  el.classList.add("active");',
    '  var jid=el.getAttribute("data-jid");',
    '  var agentId=el.getAttribute("data-agent-id");',
    '  var chName=el.querySelector(".ch-name");',
    '  document.getElementById("ctx-title").textContent=chName?chName.textContent:agentId;',
    '  document.getElementById("ctx-subtitle").textContent=agentId+" \\u2014 "+jid;',
    '  document.getElementById("ctx-empty").style.display="none";',
    '  document.getElementById("editor-view").style.display="flex";',
    '  updateUrl(agentId,jid);',
    '  var qs="agent_id="+encodeURIComponent(agentId)',
    '    +"&jid="+encodeURIComponent(jid)',
    '    +"&folder="+encodeURIComponent(el.getAttribute("data-folder"))',
    '    +"&server_folder="+encodeURIComponent(el.getAttribute("data-server-folder"))',
    '    +"&agent_context_folder="+encodeURIComponent(el.getAttribute("data-agent-context-folder"))',
    '    +"&channel_folder="+encodeURIComponent(el.getAttribute("data-channel-folder"))',
    '    +"&category_folder="+encodeURIComponent(el.getAttribute("data-category-folder"));',
    '  fetch("/api/context/layers?"+qs).then(function(r){return r.json();}).then(function(data){',
    '    layerData=data;',
    '    ["channel","agent","category","server"].forEach(function(l){',
    '      var dot=document.getElementById("dot-"+l);',
    '      if(dot)dot.className=layerData[l]&&layerData[l].exists?"dot exists":"dot missing";',
    '    });',
    '    document.querySelectorAll(".layer-tab").forEach(function(t){',
    '      t.classList.toggle("active",t.getAttribute("data-layer")===currentLayer);',
    '    });',
    '    loadLayerContent(currentLayer);',
    '    var sb=document.getElementById("save-bar");if(sb)sb.classList.add("visible");',
    '  }).catch(function(err){console.error("Failed to load context:",err);});',
    '}',
    '',
    'var layerTabs=document.getElementById("layer-tabs");',
    'if(layerTabs)layerTabs.addEventListener("click",function(e){',
    '  var tab=e.target.closest("[data-switch-layer]");if(!tab)return;',
    '  var layer=tab.getAttribute("data-layer");',
    '  currentLayer=layer;',
    '  document.querySelectorAll(".layer-tab").forEach(function(t){',
    '    t.classList.toggle("active",t.getAttribute("data-layer")===layer);',
    '  });',
    '  loadLayerContent(layer);updateUrl();',
    '});',
    '',
    'function loadLayerContent(layer){',
    '  var info=layerData[layer];',
    '  if(!info||!info.path){',
    '    var pd=document.getElementById("path-display");if(pd)pd.textContent="No path for this layer";',
    '    if(editor){monacoReady=false;editor.setValue("");monacoReady=true;}',
    '    originalContent="";dirty=false;updateSaveBar();updatePreview("");return;',
    '  }',
    '  var pd2=document.getElementById("path-display");if(pd2)pd2.textContent=info.path+"/CLAUDE.md";',
    '  var content=info.content||"";originalContent=content;',
    '  if(editor){monacoReady=false;editor.setValue(content);monacoReady=true;}',
    '  dirty=false;updateSaveBar();updatePreview(content);',
    '}',
    '',
    'var viewToggle=document.querySelector(".view-toggle");',
    'if(viewToggle)viewToggle.addEventListener("click",function(e){',
    '  var btn=e.target.closest("[data-set-view]");if(!btn)return;',
    '  var view=btn.getAttribute("data-view");currentView=view;',
    '  document.querySelectorAll(".view-toggle button").forEach(function(b){',
    '    b.classList.toggle("active",b.getAttribute("data-view")===view);',
    '  });',
    '  var ep=document.getElementById("editor-pane"),pp=document.getElementById("preview-pane");',
    '  if(ep)ep.classList.toggle("hidden",view==="preview");',
    '  if(pp)pp.classList.toggle("hidden",view==="editor");',
    '  if(editor)editor.layout();updateUrl();',
    '});',
    '',
    'function updatePreview(content){',
    '  var el=document.getElementById("preview-pane");if(!el)return;',
    '  if(!content){el.innerHTML="<p style=\\"color:var(--text-dim)\\">No content.</p>";return;}',
    '  if(typeof marked!=="undefined")el.innerHTML=marked.parse(content);',
    '  else el.textContent=content;',
    '}',
    '',
    'function updateSaveBar(){',
    '  var s=document.getElementById("save-status"),sb=document.getElementById("btn-save"),rb=document.getElementById("btn-revert");',
    '  if(!s)return;',
    '  if(dirty){s.textContent="Unsaved changes";s.className="status unsaved";if(sb)sb.disabled=false;if(rb)rb.disabled=false;}',
    '  else{s.textContent="No changes";s.className="status";if(sb)sb.disabled=true;if(rb)rb.disabled=true;}',
    '}',
    '',
    'function saveChanges(){',
    '  var info=layerData[currentLayer];if(!info||!info.path)return;',
    '  var content=editor?editor.getValue():"";',
    '  var s=document.getElementById("save-status"),sb=document.getElementById("btn-save");',
    '  if(s){s.textContent="Saving...";s.className="status saving";}if(sb)sb.disabled=true;',
    '  fetch("/api/context/file",{method:"PUT",headers:{"Content-Type":"application/json"},',
    '    body:JSON.stringify({path:info.path,content:content})})',
    '  .then(function(r){if(!r.ok)return r.json().then(function(d){throw new Error(d.error);});return r.json();})',
    '  .then(function(){',
    '    originalContent=content;dirty=false;info.content=content;info.exists=true;',
    '    var dot=document.getElementById("dot-"+currentLayer);if(dot)dot.className="dot exists";',
    '    if(s){s.textContent="Saved";s.className="status saved";}if(sb)sb.disabled=true;',
    '    var rb=document.getElementById("btn-revert");if(rb)rb.disabled=true;',
    '    setTimeout(function(){if(!dirty&&s){s.textContent="No changes";s.className="status";}},2000);',
    '  }).catch(function(err){',
    '    if(s){s.textContent="Error: "+(err.message||"Save failed");s.className="status error";}if(sb)sb.disabled=false;',
    '  });',
    '}',
    '',
    'var btnSave=document.getElementById("btn-save");if(btnSave)btnSave.addEventListener("click",saveChanges);',
    'var btnRevert=document.getElementById("btn-revert");',
    'if(btnRevert)btnRevert.addEventListener("click",function(){',
    '  if(editor){monacoReady=false;editor.setValue(originalContent);monacoReady=true;}',
    '  dirty=false;updateSaveBar();updatePreview(originalContent);',
    '});',
    '',
    'var params=new URLSearchParams(location.search);',
    'var initAgent=params.get("agent"),initChannel=params.get("channel");',
    'var initLayer=params.get("layer"),initView=params.get("view");',
    'if(initLayer&&["channel","category","server","agent"].indexOf(initLayer)!==-1)currentLayer=initLayer;',
    'if(initView&&["split","editor","preview"].indexOf(initView)!==-1){currentView=initView;',
    '  var vtBtns=document.querySelectorAll(".view-toggle button");',
    '  vtBtns.forEach(function(b){b.classList.toggle("active",b.getAttribute("data-view")===initView);});',
    '  var ep=document.getElementById("editor-pane"),pp=document.getElementById("preview-pane");',
    '  if(ep)ep.classList.toggle("hidden",initView==="preview");',
    '  if(pp)pp.classList.toggle("hidden",initView==="editor");',
    '}',
    'if(initAgent&&initChannel){',
    '  var ag=document.querySelector(".agent-group[data-agent-id=\\""+CSS.escape(initAgent)+"\\"]");',
    '  if(ag){',
    '    ag.querySelector(".chevron").classList.add("open");',
    '    ag.querySelector(".channel-list").classList.add("open");',
    '    var ci=ag.querySelector(".channel-item[data-jid=\\""+CSS.escape(initChannel)+"\\"]");',
    '    if(ci)setTimeout(function(){selectChannel(ci);},0);',
    '  }',
    '}',
    '',
    'window.__cleanup=function(){',
    '  if(editor){editor.dispose();editor=null;monacoReady=false;}',
    '};',
  ].join('\n');
}

function ipcScript(): string {
  return [
    'var queueBody=document.getElementById("queue-body");',
    'if(!queueBody&&!document.getElementById("stat-processing"))return;',
    '',
    'var pollTimer=setInterval(function(){',
    '  fetch("/api/ipc/queue").then(function(r){return r.json();}).then(function(details){',
    '    var tb=document.getElementById("queue-body");if(!tb)return;',
    '    var sg=document.getElementById("stat-groups");if(sg)sg.textContent=String(details.length);',
    '    if(details.length===0){tb.innerHTML="";return;}',
    '    tb.innerHTML=details.map(function(g){',
    '      var ms=g.messageLane.idle?"idle":g.messageLane.active?"active":"off";',
    '      var ts=g.taskLane.active?"active":"off";',
    '      var ti=g.taskLane.activeTask?window.__esc(g.taskLane.activeTask.taskId)+" ("+fmtMs(g.taskLane.activeTask.runningMs)+")":"\\u2014";',
    '      return "<tr><td class=\\"folder-key\\">"+window.__esc(g.folderKey)+"</td>"',
    '        +"<td><span class=\\"lane-badge lane-"+ms+"\\">"+ms+"</span></td>"',
    '        +"<td>"+g.messageLane.pendingCount+"</td>"',
    '        +"<td><span class=\\"lane-badge lane-"+ts+"\\">"+ts+"</span></td>"',
    '        +"<td>"+g.taskLane.pendingCount+"</td>"',
    '        +"<td class=\\"task-info\\">"+ti+"</td>"',
    '        +"<td>"+(g.retryCount>0?"<span class=\\"retry-count\\">"+g.retryCount+"</span>":"\\u2014")+"</td></tr>";',
    '    }).join("");',
    '  }).catch(function(){});',
    '},5000);',
    '',
    'var eventPollTimer=setInterval(function(){',
    '  fetch("/api/ipc/events?count=50").then(function(r){return r.json();}).then(function(events){',
    '    var tb=document.getElementById("events-body");if(!tb)return;',
    '    var se=document.getElementById("stat-events");if(se)se.textContent=String(events.length);',
    '    tb.innerHTML=events.map(function(e){',
    '      var kc=(e.kind||"").indexOf("error")!==-1||(e.kind||"").indexOf("blocked")!==-1?"event-error"',
    '        :(e.kind||"").indexOf("suppressed")!==-1?"event-warn":"event-ok";',
    '      var t=new Date(e.timestamp).toLocaleTimeString("en-US",{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"});',
    '      return "<tr class=\\""+kc+"\\"><td class=\\"event-time\\">"+window.__esc(t)+"</td>"',
    '        +"<td><span class=\\"event-kind-badge\\">"+window.__esc(e.kind||"")+"</span></td>"',
    '        +"<td class=\\"event-source\\">"+window.__esc(e.sourceGroup||"")+"</td>"',
    '        +"<td class=\\"event-summary\\">"+window.__esc(e.summary||"")+"</td></tr>";',
    '    }).join("");',
    '  }).catch(function(){});',
    '},5000);',
    '',
    'function fmtMs(ms){if(ms<1000)return ms+"ms";if(ms<60000)return(ms/1000).toFixed(1)+"s";return(ms/60000).toFixed(1)+"m";}',
    '',
    'window.__cleanup=function(){clearInterval(pollTimer);clearInterval(eventPollTimer);};',
  ].join('\n');
}
